# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 728c8a3fdd5af0243d5082fdc25d946740af52cfe7f522b5c21a4ed1dcdf0eff52647c188ab5de31a8f06e5b9967c1755ea558a39ba2ce0948c17d0168457795

test:
  secret_key_base: b94d99d5f47f301f97af24817c0a5d4efe524098228601deb2e34677f3a59d528fc5a27012abbd132c95acf2b9aacfbca8f2661182e50e1d53d1551e3852f07a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
